version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - "major"
          - "minor"
          - "patch"
    open-pull-requests-limit: 0
