#!/usr/bin/env bash

#########################################
#             Unit tests
#########################################

file=arkscript

if [ -f build/Release/${file}.exe ]; then
    ark=./build/Release/${file}.exe
elif [ -f build/${file} ]; then
    ark=./build/${file}
else
    echo "No ark executable found" && exit 1
fi

$ark tests/arkscript/unittests.ark --lib lib/ || exit 1
$ark lib/std/tests/all.ark         --lib lib/ || exit 1

#########################################
#          Integration tests
#########################################

(cd tests/cpp/ ; echo ; bash ./run-tests)

#########################################
#              AST tests
#########################################

(cd tests/ast/ ; echo ; bash ./run-tests)

#########################################
#             Module tests
#########################################

(echo ; source ./lib/modules/.github/run-tests)
