#!/usr/bin/env bash

#########################################
#             Unit tests
#########################################

if [ -f build/Release/ark.exe ]; then
    ./build/Release/ark.exe tests/arkscript/unittests.ark --lib lib/ || exit 1
elif [ -f build/ark ]; then
    ./build/ark tests/arkscript/unittests.ark --lib lib/ || exit 1
else
    echo "No ark executable found" && exit 1
fi

#########################################
#          Integration tests
#########################################

cd tests/cpp/
# blank line for formatting (and easier CI logs analysis)
echo
bash ./run-tests