/**
 * @file IRCompiler.hpp
 * @author Lexy Plateau (lexplt.dev@gmail.com)
 * @brief Compile the intermediate representation to bytecode
 * @date 2024-10-05
 *
 * @copyright Copyright (c) 2024-2026
 *
 */

#ifndef ARK_COMPILER_INTERMEDIATEREPRESENTATION_IRCOMPILER_HPP
#define ARK_COMPILER_INTERMEDIATEREPRESENTATION_IRCOMPILER_HPP

#include <vector>
#include <string>

#include <Ark/Utils/Platform.hpp>
#include <Ark/Utils/Logger.hpp>
#include <Ark/Compiler/Common.hpp>
#include <Ark/Compiler/Pass.hpp>
#include <Ark/Compiler/ValTableElem.hpp>
#include <Ark/Compiler/IntermediateRepresentation/Entity.hpp>

namespace Ark::internal
{
    class ARK_API IRCompiler final : public Pass
    {
    public:
        /**
         * @brief Create a new IRCompiler
         *
         * @param debug debug level
         */
        explicit IRCompiler(unsigned debug);

        /**
         * @brief Turn a given IR into bytecode
         *
         * @param pages list of lists of IR entities generated by the compiler
         * @param symbols symbol table generated by the compiler
         * @param values value table generated by the compiler
         */
        void process(const std::vector<IR::Block>& pages, const std::vector<std::string>& symbols, const std::vector<ValTableElem>& values);

        /**
         * @brief Dump the IR given to `process` to an output stream
         *
         * @param stream output stream
         */
        void dumpToStream(std::ostream& stream) const;

        /**
         * @brief Return the constructed bytecode object
         *
         * @return const bytecode_t&
         */
        [[nodiscard]] const bytecode_t& bytecode() const noexcept;

    private:
        bytecode_t m_bytecode;
        std::vector<IR::Block> m_ir;
        std::vector<std::string> m_filenames;

        void compile();

        /**
         * @brief Push a word (4 bytes) to the m_bytecode
         * @param word
         */
        void pushWord(const Word& word);

        /**
         * @brief Push the file headers (magic, version used, timestamp)
         *
         */
        void pushFileHeader() noexcept;

        void pushSymbolTable(const std::vector<std::string>& symbols);
        void pushValueTable(const std::vector<ValTableElem>& values);
        void pushFilenameTable();
        void pushInstLocTable(const std::vector<IR::Block>& pages);
    };
}

#endif  // ARK_COMPILER_INTERMEDIATEREPRESENTATION_IRCOMPILER_HPP
