/**
 * @file IRInliner.hpp
 * @author Lexy Plateau (lexplt.dev@gmail.com)
 * @brief Try to inline IR blocks
 * @date 2026-07-11
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef ARK_COMPILER_INTERMEDIATEREPRESENTATION_IRINLINER_HPP
#define ARK_COMPILER_INTERMEDIATEREPRESENTATION_IRINLINER_HPP

#include <Ark/Utils/Platform.hpp>
#include <Ark/Compiler/Pass.hpp>
#include <Ark/Compiler/ValTableElem.hpp>
#include <Ark/Compiler/IntermediateRepresentation/Entity.hpp>

#include <utility>
#include <vector>
#include <string>

namespace Ark::internal
{
    struct BlockInfo
    {
        long constant_id;
        std::size_t addr;
        std::string name;
        std::optional<std::size_t> symbol_id;
    };

    class ARK_API IRInliner final : public Pass
    {
    public:
        /**
         * @brief Create a new IRInliner
         *
         * @param debug debug level
         */
        explicit IRInliner(unsigned debug);

        /**
         * @brief Attempt to inline IR blocks to avoid function calls when possible
         *
         * @param pages list of lists of IR entities generated by the compiler
         * @param symbols symbol table generated by the compiler
         * @param values value table generated by the compiler
         */
        void process(const std::vector<IR::Block>& pages, const std::vector<std::string>& symbols, const std::vector<ValTableElem>& values);

        /**
         * @brief Return the IR blocks (one per scope)
         *
         * @return const std::vector<Block>&
         */
        [[nodiscard]] const std::vector<IR::Block>& intermediateRepresentation() const noexcept;

    private:
        std::vector<IR::Block> m_ir;
        std::vector<std::string> m_symbols;
        std::vector<ValTableElem> m_values;
        std::vector<BlockInfo> m_funcs;

        enum class CallKind
        {
            Symbol,
            Constant
        };

        /**
         * @brief Check if a block can be inlined in another one
         *
         * @param candidate block to inline
         * @param source where the inlining will take place
         * @return true if the candidate can be inlined
         */
        [[nodiscard]] static bool canBeInlined(const IR::Block& candidate, const IR::Block& source) noexcept;

        [[nodiscard]] std::optional<BlockInfo> blockToInlineInCall(CallKind kind, const std::vector<IR::Block>& pages, std::optional<uint16_t> maybe_id, const IR::Block& current) const noexcept;

        void inlineBlock(const IR::Block& inlinee, IR::Block& destination);

        void extractPagesMetadata(const std::vector<IR::Block>& pages);

        [[nodiscard]] std::optional<BlockInfo> findBlockBy(CallKind kind, uint16_t id) const noexcept;
    };
}

#endif  // ARK_COMPILER_INTERMEDIATEREPRESENTATION_IRINLINER_HPP
