/**
 * @file IROptimizer.hpp
 * @author Alexandre Plateau (lexplt.dev@gmail.com)
 * @brief Optimize IR based on IR entity grouped by 2 (or more)
 * @date 2024-10-11
 *
 * @copyright Copyright (c) 2024-2025
 *
 */
#ifndef ARK_COMPILER_INTERMEDIATEREPRESENTATION_IROPTIMIZER_HPP
#define ARK_COMPILER_INTERMEDIATEREPRESENTATION_IROPTIMIZER_HPP

#include <Ark/Platform.hpp>
#include <Ark/Logger.hpp>
#include <Ark/Compiler/ValTableElem.hpp>
#include <Ark/Compiler/IntermediateRepresentation/Entity.hpp>

#include <optional>
#include <functional>

namespace Ark::internal
{
    class ARK_API IROptimizer final
    {
    public:
        /**
         * @brief Create a new IROptimizer
         *
         * @param debug debug level
         */
        explicit IROptimizer(unsigned debug);

        /**
         * @brief Turn a given IR into bytecode
         *
         * @param pages list of lists of IR entities generated by the compiler
         * @param symbols symbol table generated by the compiler
         * @param values value table generated by the compiler
         */
        void process(const std::vector<IR::Block>& pages, const std::vector<std::string>& symbols, const std::vector<ValTableElem>& values);

        /**
         * @brief Return the IR blocks (one per scope)
         *
         * @return const std::vector<Block>&
         */
        [[nodiscard]] const std::vector<IR::Block>& intermediateRepresentation() const noexcept;

    private:
        using Entities = std::vector<IR::Entity>;
        using Condition_t = std::function<bool(const Entities&)>;
        using Replacement_t = std::function<IR::Entity(const Entities&)>;

        struct Rule
        {
            std::vector<Instruction> expected;
            Condition_t condition;            ///< Additional condition to match
            Replacement_t createReplacement;  ///< Create the replacement instructions from given context

            Rule(
                std::vector<Instruction>&& input,
                Instruction replacement,
                Condition_t&& cond = [](const Entities&) {
                    return true;
                }) :
                expected(std::move(input)), condition(std::move(cond)), createReplacement([replacement](const Entities& e) {
                    return IR::Entity(replacement, e[0].primaryArg(), e[1].primaryArg());
                })
            {}

            Rule(
                std::vector<Instruction>&& input,
                Condition_t&& cond,
                Replacement_t&& repl) :
                expected(std::move(input)), condition(std::move(cond)), createReplacement(std::move(repl))
            {}

            Rule(
                std::vector<Instruction>&& input,
                Replacement_t&& repl) :
                expected(std::move(input)), condition([](const Entities&) {
                    return true;
                }),
                createReplacement(std::move(repl))
            {}
        };

        std::vector<Rule> m_ruleset_two;
        std::vector<Rule> m_ruleset_three;

        Logger m_logger;
        std::vector<IR::Block> m_ir;
        std::vector<std::string> m_symbols;
        std::vector<ValTableElem> m_values;

        [[nodiscard]] bool match(const std::vector<Instruction>& expected_insts, const Entities& entities) const;
        std::optional<IR::Entity> replaceWithRules(const std::vector<Rule>& rules, const Entities& entities);

        [[nodiscard]] bool isPositiveNumberInlinable(uint16_t id) const;
        [[nodiscard]] uint16_t numberAsArg(uint16_t id) const;
    };
}

#endif  // ARK_COMPILER_INTERMEDIATEREPRESENTATION_IROPTIMIZER_HPP
