repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.expected^'
      - id: end-of-file-fixer
        exclude: '\.expected^'
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'ad270fb9db427f956ce8eb50c74617ed117b9bfc'
    hooks:
      - id: clang-format
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: '336fdd7c3cab698ead0b1c95157b9e74d3906b62'
    hooks:
      - id: cppcheck
        args: [
          "--platform=unix64",
          "--language=c++",
          "--inline-suppr",
          "--suppressions-list=cppcheck-suppressions.txt",
          "--check-level=exhaustive",
          "--force",
          "-Iinclude",
          "-j", "8",
          "--cppcheck-build-dir=cache-cppcheck"
        ]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v3.2.0'
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ ]
      # build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
      # ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
      # docs: Documentation only changes
      # feat: A new feature
      # fix: A bug fix
      # perf: A code change that improves performance
      # refactor: A code change that neither fixes a bug nor adds a feature
      # style: Changes that do not affect the meaning of the code (white-space, formatting, missing semicolons, etc)
      # test: Adding missing tests or correcting existing tests
