services: docker
language: cpp
dist: xenial

jobs:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8
        - CXX_COMPILER=g++-8

    - os: osx
      # osx_image: xcode11.6
      env:
        - MATRIX_EVAL="brew install gcc && brew link gcc"
        - C_COMPILER=clang
        - CXX_COMPILER=/usr/local/bin/g++-9

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
            - libc++-8-dev
            - libstdc++-8-dev
            - libc++abi-8-dev
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
        - C_COMPILER=clang-8
        - CXX_COMPILER=clang++-8
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - CXXFLAGS="-stdlib=libc++"
        - LIBCXX=On

    - os: windows

before_script:
- |-
    case $TRAVIS_OS_NAME in
      osx)
        eval "${MATRIX_EVAL}"
        ;;
    esac

script: ./.github/travis.sh
