services: docker

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - gcc-8
            - g++-8
            - clang-8
      env:
        - C_COMPILER=clang-8 CXX_COMPILER=clang++-8

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script:
  - cmake -H. -Bbuild -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=Release -DARK_BUILD_EXE=1
  - cmake --build build --config Release
  - sudo cmake --install build --config Release
  - build/Ark tests/unittest.ark
