services: docker

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - os: osx
      osx_image: xcode11
      compiler:
          - clang
          - gcc
      addons:
        homebrew:
          packages:
            - llvm
          update: true
      env:
        - C_COMPILER=clang CXX_COMPILER=clang++

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            #- llvm-toolchain-trusty-7.0
            #- sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7.0 main'
            #  key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          #packages:
            #- clang-7
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
        - C_COMPILER=clang CXX_COMPILER=clang++
        - LINKER_FLAGS="-stdlib=libc++ -lc++abi"
        - CXXFLAGS="-stdlib=libc++"

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script: ./.github/travis.sh
