services: docker

before_install:
  - sudo apt-get install -y llvm-toolchain-xenial-9

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
      env:
        - C_COMPILER=gcc-8 CXX_COMPILER=g++-8

    - os: osx
      osx_image: xcode11
      compiler:
          - clang
          - gcc
      addons:
        homebrew:
          packages:
            - llvm
          update: true
      env:
        - C_COMPILER=clang CXX_COMPILER=clang++

    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - clang-9
      env:
        - C_COMPILER=clang-9 CXX_COMPILER=clang++-9

    - os: windows
      dist: 1803-containers
      env: VERSION=1.11 VARIANT=windows/windowsservercore-1803

sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

script: ./.github/travis.sh
