#!/usr/bin/env bash

file=arkscript

if [ -f ../../build/Release/${file}.exe ]; then
    ark=../../build/Release/${file}.exe
elif [ -f ../../build/${file} ]; then
    ark=../../build/${file}
else
    echo "No $file executable found" && exit 1
fi

$ark unittests.ark --lib ../../lib/ || exit 1
$ark ../../lib/std/tests/all.ark --lib ../../lib/ || exit 1
