name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "Steps to reproduce the behavior: ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What ArkScript version are you seeing the problem on?
      placeholder: master, dev, v3.2.0...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant code & log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Documentation
      options:
        - label: I have read existing related documentation before submitting this report
          required: true
        - label: I have searched for an existing issue before posting
          required: true
