name: Bug Report
description: File a bug report
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: "Steps to reproduce the behavior: ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: What ArkScript version are you seeing the problem on?
      placeholder: master, dev, v3.5.0...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you running?
      options:
        - Windows
        - Linux
        - MacOS
        - Android
      default: 0
    validations:
      required: true
  - type: dropdown
    id: compiler
    attributes:
      label: Compiler used
      description: In case you compiled ArkScript yourself, what compiler did you use?
      options:
        - Clang
        - GCC
        - MSVC
        - Clang-Cl
        - MinGw
        - Other (please specify)
    validations:
      required: false
  - type: input
    id: compiler_version
    attributes:
      label: Compiler version used
      description: What was the version of your compiler used to compile ArkScript?
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant code & log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Documentation
      options:
        - label: I have read existing related documentation before submitting this report
          required: true
        - label: I have searched for an existing issue before posting
          required: true
