name: Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: checkboxes
    id: type-of-change
    attributes:
      label: Is it a big modification to the language? Leave it if you don't know
      options:
        - label: Breaking change
        - label: Compiler/syntax modifications
        - label: Runtime modifications (standard library, modules, packages...)
