#include <CLI/Formatter.hpp>

#include <iostream>
#include <utility>
#include <fmt/core.h>

#include <Ark/Exceptions.hpp>
#include <Ark/Compiler/Common.hpp>

using namespace Ark;
using namespace Ark::internal;

Formatter::Formatter(std::string filename, bool dry_run) :
    m_filename(std::move(filename)), m_dry_run(dry_run), m_parser(/* interpret= */ false)
{}

void Formatter::run()
{
    try
    {
        m_parser.processFile(m_filename);
        // TODO remove trailing whitespaces on each line

        // remove useless surrounding begin (generated by the parser)
        if (isBeginBlock(m_parser.ast()))
        {
            std::size_t previous_line = 0;
            for (std::size_t i = 1, end = m_parser.ast().constList().size(); i < end; ++i)
            {
                const Node node = m_parser.ast().constList()[i];
                if (node.line() - previous_line > 1 && !m_output.empty())
                    m_output += "\n";
                previous_line = lineOfLastNodeIn(node);
                m_output += format(node, 0, false) + "\n";
            }
        }
        else
            m_output = format(m_parser.ast(), 0, false);

        if (!m_dry_run)
        {
            std::ofstream stream(m_filename);
            stream << m_output;
        }
    }
    catch (const CodeError& e)
    {
        Diagnostics::generate(e);
    }
}

const std::string& Formatter::output() const
{
    return m_output;
}

bool Formatter::isListStartingWithKeyword(const Ark::internal::Node& node, Ark::internal::Keyword keyword)
{
    return node.isListLike() && !node.constList().empty() && node.constList()[0].nodeType() == NodeType::Keyword && node.constList()[0].keyword() == keyword;
}

bool Formatter::isBeginBlock(const Node& node)
{
    return isListStartingWithKeyword(node, Keyword::Begin);
}

bool Formatter::isFuncDef(const Ark::internal::Node& node)
{
    return isListStartingWithKeyword(node, Keyword::Fun);
}

bool Formatter::isFuncCall(const Ark::internal::Node& node)
{
    return node.isListLike() && !node.constList().empty() && node.constList()[0].nodeType() == NodeType::Symbol;
}

bool Formatter::isPlainValue(const Ark::internal::Node& node)
{
    switch (node.nodeType())
    {
        case NodeType::Symbol: [[fallthrough]];
        case NodeType::Number: [[fallthrough]];
        case NodeType::String: [[fallthrough]];
        case NodeType::Field: return true;

        default:
            return true;
    }
}

std::size_t Formatter::lineOfLastNodeIn(const Ark::internal::Node& node)
{
    if (node.isListLike() && !node.constList().empty())
        return lineOfLastNodeIn(node.constList().back());
    else
        return node.line();
}

bool Formatter::should_split_on_newline(const Ark::internal::Node& node)
{
    std::string formatted = format(node, 0, false);
    std::string::size_type sz = formatted.find_first_of('\n');

    bool is_long_line = !((sz < 32 || (sz == std::string::npos && formatted.size() < 32)));
    if ((isBeginBlock(node) && node.comment().empty()) || isFuncCall(node))
        return false;
    else if (is_long_line || (node.isListLike() && node.constList().size() > 1) || !node.comment().empty())
        return true;
    return false;
}

std::string Formatter::format(const Ark::internal::Node& node, std::size_t indent, bool after_newline)
{
    const std::string prefix = std::string(indent * 4, ' ');

    std::string output;
    if (!node.comment().empty())
    {
        std::string comment = node.comment();
        output += prefix;
        for (std::size_t i = 0, end = comment.size(); i < end; ++i)
        {
            output += comment[i];
            if (comment[i] == '\n' && i != end - 1)
                output += prefix;
        }
    }
    if (after_newline)
        output += prefix;

    switch (node.nodeType())
    {
        case NodeType::Symbol:
            output += node.string();
            break;
        case NodeType::Capture:
            output += "&" + node.string();
            break;
        case NodeType::Keyword:
            output += std::string(keywords[static_cast<std::size_t>(node.keyword())]);
            break;
        case NodeType::String:
            output += fmt::format("\"{}\"", node.string());
            break;
        case NodeType::Number:
            output += fmt::format("{}", node.number());
            break;
        case NodeType::List:
            output += formatBlock(node, indent, after_newline);
            break;
        case NodeType::Spread:
            output += fmt::format("...{}", node.string());
            break;
        case NodeType::Field:
        {
            std::string field = format(node.constList()[0], indent, false);
            for (std::size_t i = 1, end = node.constList().size(); i < end; ++i)
                field += "." + format(node.constList()[1], indent, false);
            output += field;
            break;
        }
        case NodeType::Macro:
            output += formatMacro(node, indent);
            break;
        case NodeType::Unused:
            break;
    }

    return output;
}

std::string Formatter::formatBlock(const Ark::internal::Node& node, std::size_t indent, bool after_newline)
{
    if (node.constList().empty())
        return "()";

    const Node first = node.constList().front();
    if (first.nodeType() == NodeType::Keyword)
    {
        switch (first.keyword())
        {
            case Keyword::Fun:
                return formatFunction(node, indent);
            case Keyword::Let:
                [[fallthrough]];
            case Keyword::Mut:
                [[fallthrough]];
            case Keyword::Set:
                return formatVariable(node, indent);
            case Keyword::If:
                return formatCondition(node, indent);
            case Keyword::While:
                return formatLoop(node, indent);
            case Keyword::Begin:
                return formatBegin(node, indent, after_newline);
            case Keyword::Import:
                return formatImport(node, indent);
            case Keyword::Del:
                return formatDel(node, indent);
        }
    }
    else
        return formatCall(node, indent);
}

std::string Formatter::formatFunction(const Ark::internal::Node& node, std::size_t indent)
{
    const Node args_node = node.constList()[1];
    const Node body_node = node.constList()[2];

    std::string formatted_args;
    bool comment_in_args = false;

    if (args_node.isListLike())
    {
        std::string args;
        for (std::size_t i = 0, end = args_node.constList().size(); i < end; ++i)
        {
            const Node arg_i = args_node.constList()[i];
            bool has_comment = !arg_i.comment().empty();
            if (has_comment)
                comment_in_args = true;

            args += format(arg_i, indent + (comment_in_args ? 1 : 0), comment_in_args);
            if (i != end - 1)
                args += comment_in_args ? '\n' : ' ';
        }

        formatted_args = fmt::format("({}{})", (comment_in_args ? "\n" : ""), args);
    }
    else
        formatted_args = format(args_node, indent, false);

    std::string formatted_body = format(body_node, indent + 1, false);

    if (!should_split_on_newline(body_node))
        return fmt::format("(fun {} {})", formatted_args, formatted_body);
    else
        return fmt::format("(fun {}\n{})", formatted_args, format(body_node, indent + 1, true));
}

std::string Formatter::formatVariable(const Ark::internal::Node& node, std::size_t indent)
{
    std::string keyword = std::string(keywords[static_cast<std::size_t>(node.constList()[0].keyword())]);

    const Node body_node = node.constList()[2];
    std::string formatted_body = format(body_node, indent, false);

    if (!should_split_on_newline(body_node) || isFuncDef(body_node))
        return fmt::format("({} {} {})", keyword, format(node.constList()[1], indent, false), formatted_body);
    else
        return fmt::format("({} {}\n{})", keyword, format(node.constList()[1], indent, false), format(node.constList()[2], indent + 1, true));
}

std::string Formatter::formatCondition(const Ark::internal::Node& node, std::size_t indent, bool is_macro)
{
    const Node cond_node = node.constList()[1];
    const Node then_node = node.constList()[2];

    std::string formatted_cond = format(cond_node, indent, false);
    if (formatted_cond.find('\n') != std::string::npos)
        formatted_cond = format(cond_node, indent, true);

    std::string start_formatted = fmt::format(
        "({}if {}\n{}",
        is_macro ? "$" : "",
        formatted_cond,
        format(then_node, indent + 1, true));

    // if cond then
    if (node.constList().size() == 3)
        return start_formatted + ")";
    else  // if cond then else
        return fmt::format("{}\n{})", start_formatted, format(node.constList()[3], indent + 1, true));
}

std::string Formatter::formatLoop(const Ark::internal::Node& node, std::size_t indent)
{
    const Node cond_node = node.constList()[1];
    const Node body_node = node.constList()[2];
    return fmt::format("(while {} {})", format(cond_node, indent, false), format(body_node, indent + 1, false));
}

std::string Formatter::formatBegin(const Ark::internal::Node& node, std::size_t indent, bool after_newline)
{
    // only the keyword begin is present
    if (node.constList().size() == 1)
        return "{}";

    std::string output = "{\n";
    std::size_t previous_line = 0;
    // skip begin keyword
    for (std::size_t i = 1, end = node.constList().size(); i < end; ++i)
    {
        const Node child = node.constList()[i];
        // we want to preserve the node grouping by the user, but remove useless duplicate new line
        // but that shouldn't apply to the first node of the block
        if (child.line() - previous_line > 1 && i > 1)
            output += "\n";
        previous_line = lineOfLastNodeIn(child);
        if (previous_line < child.line())  // FIXME: shouldn't happen, but here we are
            previous_line = child.line();

        output += format(child, indent + (after_newline ? 1 : 0), true);
        if (i != end - 1)
            output += "\n";
    }
    output += " }";
    return output;
}

std::string Formatter::formatImport(const Ark::internal::Node& node, std::size_t indent)
{
    const Node package_node = node.constList()[1];
    std::string package;
    for (std::size_t i = 0, end = package_node.constList().size(); i < end; ++i)
    {
        package += package_node.constList()[i].string();
        if (i != end - 1)
            package += ".";
    }

    const Node symbols = node.constList()[2];
    if (symbols.nodeType() == NodeType::Symbol && symbols.string() == "*")
        package += ":*";
    else  // symbols is a list
    {
        for (const auto& sym : symbols.constList())
            package += " :" + sym.string();  // TODO: handle comments?
    }

    return fmt::format("(import {})", package);
}

std::string Formatter::formatDel(const Ark::internal::Node& node, std::size_t indent)
{
    return fmt::format("(del {})", format(node.constList()[1], indent, false));
}

std::string Formatter::formatCall(const Ark::internal::Node& node, std::size_t indent)
{
    bool is_list = false;
    if (!node.constList().empty() && node.constList().front().nodeType() == NodeType::Symbol &&
        node.constList().front().string() == "list")
        is_list = true;

    bool is_multiline = false;

    std::vector<std::string> formatted_args;
    for (std::size_t i = 1, end = node.constList().size(); i < end; ++i)
    {
        formatted_args.push_back(format(node.constList()[i], indent, false));
        // if we have at least one argument taking multiple lines, split them all on their own line
        if (formatted_args.back().find('\n') != std::string::npos)
            is_multiline = true;
    }

    std::string output = is_list ? "[" : ("(" + format(node.constList()[0], indent, false));
    for (std::size_t i = 0, end = formatted_args.size(); i < end; ++i)
    {
        const std::string formatted_node = formatted_args[i];
        if (is_multiline && formatted_args.size() > 1)
            output += "\n" + format(node.constList()[i + 1], indent + 1, true);
        else
            output += (is_list && i == 0 ? "" : " ") + formatted_node;
    }
    output += is_list ? "]" : ")";
    return output;
}

std::string Formatter::formatMacro(const Ark::internal::Node& node, std::size_t indent)
{
    if (isListStartingWithKeyword(node, Keyword::If))
        return formatCondition(node, indent, /* is_macro= */ true);

    std::string output;
    // because some macro call like ($undef ...) are considered macros and we shouldn't confuse them and write ($ $undef ...)
    if (!node.constList().empty() && node.constList().front().nodeType() == NodeType::Symbol && node.constList().front().string().starts_with('$'))
        output = "(";
    else
        output = "($ ";

    for (std::size_t i = 0, end = node.constList().size(); i < end; ++i)
    {
        output += format(node.constList()[i], indent + 1, false);
        if (i != end - 1)
            output += " ";
    }

    return output + ")";
}
