---
name: "Setup tests"
description: "Unpack necessary artifacts, updates compilers"
inputs:
  os_name:
    description: 'OS name the CI runs on ; Ubuntu|Windows|MacOS'
    required: true
  compiler_version:
    description: 'version of the compiler'
    required: true

runs:
  using: "composite"
  steps:
    - name: Download artifact
      id: download
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.config.artifact }}
        path: build

    - name: Download temp artifact
      id: download-artifact
      uses: actions/download-artifact@v4
      with:
        name: temp-${{ matrix.config.artifact }}
        path: artifact

    - name: Update GNU compilers
      if: startsWith(matrix.config.name, 'Ubuntu GCC')
      shell: bash
      run: |
        sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt-get -yq install libstdc++6

    - name: Update LLVM compilers
      if: startsWith(inputs.os_name, 'macos')
      shell: bash
      run: |
        brew install llvm@${{ inputs.compiler_version }}

    - shell: bash
      run: |
        mv build/lib/*.arkm lib/
        chmod u+x build/arkscript
        cp -r artifact/tests/unittests/* tests/unittests/
        cp artifact/unittests .
        chmod u+x unittests

    - shell: bash
      if: startsWith(matrix.config.name, 'Windows')
      run: |
        cp build/*.dll .
