---
name: "Install compilers and dependencies"

runs:
  using: "composite"
  steps:
    - name: Install MacOS dependencies
      if: startsWith(matrix.config.name, 'MacOS')
      shell: bash
      run: env HOMEBREW_NO_AUTO_UPDATE=1 brew install openssl

    - name: Download Windows dependencies
      if: startsWith(matrix.config.name, 'Windows')
      shell: pwsh
      run: |
        Invoke-RestMethod -Uri https://www.sqlite.org/2022/sqlite-dll-win64-x64-${Env:SQLITE_VERSION}.zip -OutFile sqlite.zip
        Invoke-RestMethod -Uri https://www.sqlite.org/2022/sqlite-amalgamation-${Env:SQLITE_VERSION}.zip  -OutFile amalgation.zip
        Expand-Archive sqlite.zip -DestinationPath sqlite_lib
        Expand-Archive amalgation.zip -DestinationPath sqlite_code
        cd sqlite_lib
        lib /DEF:sqlite3.def /OUT:sqlite3.lib /MACHINE:x64
