name: clang-format check

on: [pull_request]

jobs:
  check:
    name: Formatting check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        path:
          - 'src'
          - 'include'

    steps:
      - uses: actions/checkout@v2

      - name: Run clang-format check for C++
        uses: HorstBaerbel/action-clang-format@1.5
        with:
          scandir: ${{ matrix.path }}
          style: 'file'
