name: Build and push Docker images

on:
  push:
    branches: [ dev ]
    tags: [ '*' ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and push stable Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: arkscript/stable
        dockerfile: Dockerfile
        # tag with the git commit SHA
        tag_with_sha: true
        tags: latest
        # push the image only if the event that kicked off the workflow was a push of a git tah
        push: ${{ startsWith(github.ref, 'refs/tags/') }}

    - name: Build and push nightly Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: arkscript/nightly
        dockerfile: Dockerfile
        # tag with the git commit SHA
        tag_with_sha: true
        tags: latest