name: "CMake - MSVC"

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  BUILD_TYPE: Release
  CC: cl
  CXX: cl

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config:
        - {
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
          }

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake Ark
      shell: bash
      run: |
        cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DARK_BUILD_EXE=On -DARK_BUILD_MODULES=On -DARK_MOD_ALL=On

    - name: Configure CMake Integration tests
      shell: bash
      run: |
        cd tests/cpp
        cmake -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX

    - name: Build Ark
      shell: bash
      run: |
        cmake --build build --config $BUILD_TYPE

    - name: Build Integration tests
      shell: bash
      run: |
        cd tests/cpp
        cmake --build build --config $BUILD_TYPE

    - name: Tests
      shell: bash
      run: bash .github/launch-tests

    - name: Organize files for upload
      shell: bash
      run: |
        mkdir -p artifact/lib
        cp build/$BUILD_TYPE/ark.exe artifact
        cp lib/*.arkm artifact/lib
        cp -r lib/std/ artifact/lib
        rm -rf artifact/lib/std/.git

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ark-windows-msvc-version
        path: artifact
