#!/usr/bin/env bash

file=arkscript

if [ -f ../../cmake-build-debug/${file} ]; then
    ark=../../cmake-build-debug/${file}
elif [ -f ../../build/Release/${file}.exe ]; then
    ark=../../build/Release/${file}.exe
elif [ -f ../../build/${file} ]; then
    ark=../../build/${file}
else
    echo "No $file executable found" && exit 1
fi

Reset='\033[0m'
Red='\033[0;31m'
Green='\033[0;32m'
Yellow='\033[0;33m'
Purple='\033[0;35m'
Cyan='\033[0;36m'

passed=0
failed=0

for f in ./**/*.ark; do
    output=$($ark "$f" --lib ../../lib 2>&1 | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]+;?)*)?[mGK]//g")
    expected=$(cat "${f%.*}.expected")

    case "$output" in
      *"$expected"* )
        echo -e "${Green}PASSED${Reset} ${f%.*}"
        ((passed=passed+1))
        ;;

      *)
        echo -e "${Red}FAILED${Reset} ${f%.*}"
        ((failed=failed+1))
        echo -e "    ${Yellow}Output${Reset}:"
        diff -a -y <(echo -e "$output") <(echo -e "$expected")
        ;;
    esac
done

echo "  ------------------------------"
echo -e "  ${Cyan}${passed}${Reset} passed, ${Purple}${failed}${Reset} failed"

if [[ $failed != 0 ]]; then
    exit 1
else
    exit 0
fi
